### ISSUE TITLE
缺少配置文件User.Json

### ISSUE THREAD

**Issue by SullenWu** [flipturn14/wechat_bot#2]
Traceback (most recent call last):
  File "E:\wechat_bot\main.py", line 1, in <module>
    from python.client.wxclient import ws
  File "E:\wechat_bot\python\client\wxclient.py", line 13, in <module>
    from python.revChat.poe.poe import Poe
  File "E:\wechat_bot\python\revChat\poe\poe.py", line 72, in <module>
    creList = configure()
  File "E:\wechat_bot\python\revChat\poe\poe.py", line 66, in configure
    raise Exception("No config file found.")
Exception: No config file found.

**Comment by flipturn14** [comment]
自己新建一个空的文件文件就行。
